export const staticCinemas = [
    {
        id: 1,
        name_hk: "MOViE MOViE Pacific Place (金鐘)",
        name_simplified: "MOViE MOViE Pacific Place (金钟)",
        name_en: "MOViE MOViE Pacific Place (Admiralty)",
        address_hk: "香港金鐘道88號太古廣場L1",
        address_en:
            "Address: Level 1, Pacific Place, 88 Queensway Road, Hong Kong Island",
        logo: "",
        district_id: 1,
        district_name: "香港",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 2,
        name_hk: "MOViE MOViE Cityplaza (太古城)",
        name_simplified: "MOViE MOViE Cityplaza (太古城)",
        name_en: "MOViE MOViE Cityplaza (Taikoo Shing)",
        address_hk: "香港太古城道18號太古城中心5樓",
        address_en: "5/F Cityplaza, 18 Taikoo Shing Road, Hong Kong",
        logo: "",
        district_id: 1,
        district_name: "香港",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 3,
        name_hk: "PALACE ifc",
        name_simplified: "PALACE ifc",
        name_en: "PALACE ifc",
        address_hk: "香港中環金融街8號國際金融中心商場一樓",
        address_en: "Podium L1, ifc Mall, 8 Finance Street, Central",
        logo: "",
        district_id: 1,
        district_name: "香港",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 4,
        name_hk: "GALA CINEMA (朗豪坊)",
        name_simplified: "GALA CINEMA (朗豪坊)",
        name_en: "GALA CINEMA (Langham Place)",
        address_hk: "旺角亞皆老街8號朗豪坊商場8樓",
        address_en: "Level 8, Langham Place Mall, 8 Argyle Street, Mong Kok",
        logo: "",
        district_id: 2,
        district_name: "九龙",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 5,
        name_hk: "B+ cinema MOKO (旺角東)",
        name_simplified: "B+ cinema MOKO (旺角东)",
        name_en: "B+ cinema MOKO (Mong Kok East)",
        address_hk: "香港九龍旺角太子道西193號MOKO新世紀廣場4樓",
        address_en:
            "4/F, MOKO 193 Prince Edward Road West, Mongkok, Kowloon, Hong Kong",
        logo: "",
        district_id: 2,
        district_name: "九龙",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 6,
        name_hk: "B+ cinema apm (觀塘)",
        name_simplified: "B+ cinema apm (观塘)",
        name_en: "B+ cinema apm (Kwun Tong)",
        address_hk: "九龍觀塘道418號創紀之城五期apm 6樓 L6-1舖",
        address_en:
            "Shop No. L6-1, Level 6, apm, Millennium City 5, 418 Kwun Tong Road, Kowloon, Hong Kong.",
        logo: "",
        district_id: 2,
        district_name: "九龙",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 7,
        name_hk: "Premiere Elements",
        name_simplified: "Premiere Elements",
        name_en: "Premiere Elements",
        address_hk: "九龍尖沙咀柯士甸道西1號圓方商場火區2樓2130號鋪",
        address_en: "2130, 2/F, Fire, ELEMENTS, 1 Austin Road West, Kowloon",
        logo: "",
        district_id: 2,
        district_name: "九龙",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 8,
        name_hk: "百老匯電影中心",
        name_simplified: "百老汇电影中心",
        name_en: "Broadway Cinematheque",
        address_hk: "九龍油麻地眾坊街3號駿發花園",
        address_en: "Prosperous Garden, 3 Public Square Street, Yaumatei, Kln",
        logo: "",
        district_id: 2,
        district_name: "九龙",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 9,
        name_hk: "百老匯戲院 (旺角)",
        name_simplified: "百老汇戏院(旺角)",
        name_en: "Broadway Circuit (MONGKOK)",
        address_hk: "九龍西洋菜街6-12號",
        address_en: "6-12 Sai Yeung Choi Street, Mongkok, Kowloon",
        logo: "",
        district_id: 2,
        district_name: "九龙",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 10,
        name_hk: "MY CINEMA YOHO MALL",
        name_simplified: "MY CINEMA YOHO MALL",
        name_en: "CINEMATHEQUE",
        address_hk: "新界元朗朗日路9號YOHO MALL I 1樓 1021舖",
        address_en:
            "Shop 1021, Level 1, YOHO MALL I, 9 Long Yat Road, Yuen Long",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 11,
        name_hk: "百老匯戲院 (葵芳)",
        name_simplified: "百老汇戏院(葵芳)",
        name_en: "Broadway Circuit (KWAI FONG)",
        address_hk: "新界葵芳興芳路223號新都會廣場L1-L4",
        address_en: "L1-L4 Metroplaza, 223 Hing Fong Road, Kwai Fong, NT",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 12,
        name_hk: "百老匯戲院 (荃灣)",
        name_simplified: "百老汇戏院(荃湾)",
        name_en: "Broadway Circuit (TSUEN WAN)",
        address_hk: "新界荃灣大壩街4-30號荃灣廣場L1-L3",
        address_en: "L1-L3 Tsuen Wan Plaza, 4-30 Tai Pa Street, Tsuen Wan, NT",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 13,
        name_hk: "百老匯戲院 (嘉湖)",
        name_simplified: "百老汇戏院(嘉湖)",
        name_en: "Broadway Circuit (KINGSWOOD)",
        address_hk: "新界元朗天水圍天恩路18號+WOO二期1樓",
        address_en:
            "1/F, +WOO Phase 2, 18 Tin Yan Road, Tin Shui Wai, Yuen Long, NT",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 1,
        theater_name: "百老汇院线",
    },
    {
        id: 14,
        name_hk: "英皇戲院 (銅鑼灣時代廣場)",
        name_simplified: "英皇戏院(铜锣湾时代广场)",
        name_en: "Emperor Cinemas (Times Square)",
        address_hk: "銅鑼灣勿地臣街1號時代廣場13樓",
        address_en:
            "Level 13, Times Square, 1 Matheson St, Causeway Bay",
        logo: "",
        district_id: 1,
        district_name: "香港",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 15,
        name_hk: "英皇戲院 (中環娛樂行)",
        name_simplified: "英皇戏院(中环娱乐行)",
        name_en: "Emperor Cinemas (Entertainment Building)",
        address_hk: "香港中環皇后大道中30號娛樂行3樓",
        address_en:
            "3/F, Emperor Cinemas Entertainment Building, 30 Queen's Road Central, Central, Hong Kong",
        logo: "",
        district_id: 1,
        district_name: "香港",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 16,
        name_hk: "英皇戲院 Plus+ (黃竹坑 THE SOUTHSIDE)",
        name_simplified: "英皇戏院 Plus+ (黃竹坑)",
        name_en: "Emperor Cinemas Plus+ (THE SOUTHSIDE)",
        address_hk: "黃竹坑香葉道11號THE SOUTHSIDE3樓",
        address_en:
            "3/F THE SOUTHSIDE, Wong Chuk Hang",
        logo: "",
        district_id: 1,
        district_name: "香港",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 17,
        name_hk: "英皇戲院 (尖沙咀iSQUARE)",
        name_simplified: "英皇戏院 (尖沙咀iSQUARE)",
        name_en: "Emperor Cinemas (iSQUARE)",
        address_hk: "尖沙咀彌敦道63號國際廣場7樓",
        address_en:
            "7/F, iSQUARE, 63 Nathan Road, Tsim Sha Tsui",
        logo: "",
        district_id: 2,
        district_name: "九龙",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 18,
        name_hk: "英皇戲院 (荃灣荃新天地)",
        name_simplified: "英皇戏院 (荃湾荃新天地)",
        name_en: "Emperor Cinemas (CITYWALK)",
        address_hk: "荃灣荃新天地2期",
        address_en:
            "Citywalk II, Tsuen Wan",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 19,
        name_hk: "英皇戲院 Plus+ (大圍圍方)",
        name_simplified: "英皇戏院 Plus+ (大围围方)",
        name_en: "Emperor Cinemas Plus+ (Tai Wai)",
        address_hk: "新界大圍車公廟路18號圍方5樓",
        address_en:
            "L5, The Wai, 18 Che Kung Miu Road, Tai Wai, N.T.",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 20,
        name_hk: "英皇戲院 (將軍澳康城)",
        name_simplified: "英皇戏院 (将军澳康城)",
        name_en: "Emperor Cinemas (The LOHAS)",
        address_hk: "將軍澳康城路1號, The LOHAS康城4樓",
        address_en:
            "Level 4, The LOHAS, No. 1 Lohas Park Road, Tseung Kwan O",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 21,
        name_hk: "英皇戲院 (馬鞍山新港城中心)",
        name_simplified: "英皇戏院 (马鞍山新港城中心)",
        name_en: "Emperor Cinemas (Ma On Shan)",
        address_hk: "新界馬鞍山鞍祿街18號新港城中心2樓",
        address_en:
            "L2, MOSTown, Sai Sha Road, Ma On Shan, N.T.",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
    {
        id: 22,
        name_hk: "英皇戲院 (屯門新都商場)",
        name_simplified: "英皇戏院 (屯门新都商场)",
        name_en: "Emperor Cinemas (Tuen Mun)",
        address_hk: "新界屯門屯利街2號新都商場3樓",
        address_en:
            "3/F, New Town Commercial Arcade, 2 Tuen Lee Street, Tuen Mun, N.T.",
        logo: "",
        district_id: 3,
        district_name: "新界",
        theater_id: 2,
        theater_name: "英皇戏院",
    },
];
